name: Mike Kusold
pygments: true
markdown: redcarpet
destination: _site #The directory where Jekyll will write files
timezone: America/Denver
future: false #Publish posts with a future date.
baseurl: /

author:
  name: Mike Kusold
  github: kusold
  twitter: mikekusold
