name: Mike Kusold
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
destination: _site #The directory where Jekyll will write files
timezone: America/Denver
future: false #Publish posts with a future date.
permalink: none
baseurl: /
exclude: [vendor]

author:
  name: Mike Kusold
  github: kusold
  twitter: mikekusold
